# Generated by Django 5.2.6 on 2025-12-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('conf_password', models.CharField(max_length=255)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
