# Generated by Django 5.2.6 on 2026-01-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registration_is_active_registration_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=255, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('catergory', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1200)),
                ('price', models.CharField(max_length=255)),
                ('sales_price', models.CharField(max_length=255)),
                ('initial_quantity', models.CharField(max_length=255)),
                ('low_stock_alert', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='conf_password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='userEmail',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
